//skuska.h - VSTGUI editor file, automatically generated by VSTGUI Builder

#ifndef skuska_H_
#define skuska_H_

#include "libraries/source/vstgui.h"

class skuska : public AEffGUIEditor, public CControlListener
{
  public:
    skuska(AudioEffect *effect);
    ~skuska();

  protected:
    long open(void *ptr);
    void close();

    long controlModifierClicked(CDrawContext *pContext, CControl *pControl, long button) {return 0;};

    void setParameter(long index, float value);
    void valueChanged(CDrawContext* context, CControl* control);
    void idle();

    //Controls
    CVerticalSlider *slider1;

    //Bitmaps
    CBitmap *hBack;
    CBitmap *hHSLider;
};

#endif
			