//skuska.cpp - VSTGUI editor file, automatically generated by VSTGUI Builder

#include <stdio.h>
#include "skuska.h"

//****remember to include your plugin's header file here****

enum
{
    kBack = 128,
    kHSLider,
};

//--------------------------------
skuska::skuska(AudioEffect *effect) : AEffGUIEditor(effect)
{
    slider1 = 0;

    hHSLider = 0;

    hBack  = new CBitmap(kBack);

    rect.left   = 0;
    rect.top    = 0;
    rect.right  = (short)hBack->getWidth();
    rect.bottom = (short)hBack->getHeight();
}

//--------------------------------
skuska::~skuska()
{
    if(hBack)
    {
        if(hBack->getNbReference()<=1)
        {
            hBack->forget();
            hBack = 0;
        }
        else
            hBack->forget();
    }
}

//--------------------------------
long skuska::open(void *ptr)
{
    CRect size, temp;
    CPoint point;

    AEffGUIEditor::open(ptr);

    hHSLider = new CBitmap(kHSLider);

    size(0, 0, hBack->getWidth(), hBack->getHeight());
    frame = new CFrame(size, ptr, this);
    frame->setBackground(hBack);

    //--slider1--------
    size(62, 100, (62+39), (100+39));
    point(0, 0);
    slider1 = new CVerticalSlider(size, this, 1, 100, (100+39-hHSLider->getHeight()), hHSLider, 0, point, 0);
    slider1->setValue(effect->getParameter(1));
    slider1->setTransparency(false);
    frame->addView(slider1);

    setKnobMode(kLinearMode);

    if(hHSLider)
        hHSLider->forget();

    return true;
}

//--------------------------------
void skuska::close()
{
    delete frame;
    frame = 0;

}

//--------------------------------
void skuska::setParameter(long index, float value)
{
    if(!frame)
        return;

    switch(index)
    {
    case 1:
        if(slider1)
            slider1->setValue(effect->getParameter(index));
        break;
    }
    postUpdate();
}

//--------------------------------
void skuska::valueChanged(CDrawContext* context, CControl* control)
{
    char tempch[64];
				    long tag = control->getTag();

    switch(tag)
    {
    case 1:
        effect->setParameterAutomated(tag, control->getValue());
        break;
    }
}

//--------------------------------
void skuska::idle()
{
    AEffGUIEditor::idle();

}
			